// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using recipe_guru.WebAPI.Database;

namespace recipeguru.WebAPI.Migrations
{
    [DbContext(typeof(recipeGuruContext))]
    partial class recipeGuruContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("recipe_guru.WebAPI.Database.ImageResources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ImageByteValue")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("ImageResources");
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.Kategorije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategorije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Hljebovi i Pekarska hrana"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Dorucak"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Vecera"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Rucak"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Umaci, Salate, Sosovi"
                        },
                        new
                        {
                            Id = 6,
                            Naziv = "Kokteli"
                        },
                        new
                        {
                            Id = 7,
                            Naziv = "Supe"
                        },
                        new
                        {
                            Id = 8,
                            Naziv = "Glavna Jela"
                        },
                        new
                        {
                            Id = 9,
                            Naziv = "Predjela"
                        },
                        new
                        {
                            Id = 10,
                            Naziv = "Jela iz Lonca"
                        },
                        new
                        {
                            Id = 11,
                            Naziv = "Pizze"
                        },
                        new
                        {
                            Id = 12,
                            Naziv = "Sendvici"
                        },
                        new
                        {
                            Id = 13,
                            Naziv = "Salate"
                        },
                        new
                        {
                            Id = 14,
                            Naziv = "Snacks"
                        });
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.KnjigeRecepata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("KnjigeRecepata");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KorisnikId = 2,
                            Naziv = "Ridvanovi Recepti",
                            Public = true
                        },
                        new
                        {
                            Id = 2,
                            KorisnikId = 2,
                            Naziv = "Ridvanovi Recepti #2",
                            Public = false
                        });
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.Korisnici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("UlogeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("CS_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique()
                        .HasName("CS_KorisnickoIme");

                    b.HasIndex("UlogeId");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ridvan@fit.ba",
                            Ime = "Ridvan",
                            KorisnickoIme = "admin",
                            LozinkaHash = "BecrbX8U8yPSpBGhA2jGa9y0q5k=",
                            LozinkaSalt = "CjpunY8moV5HP6BctY2aeg==",
                            Prezime = "Appa",
                            Telefon = "061234567",
                            UlogeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "ridvanclient@fit.ba",
                            Ime = "Ridvan",
                            KorisnickoIme = "ClientUser",
                            LozinkaHash = "4O3p0NzV7b15OkI8IBG7YngYN3s=",
                            LozinkaSalt = "hSakNLaRevFomUwj5rlJZg==",
                            Prezime = "Appa",
                            Telefon = "061234567",
                            UlogeId = 2
                        });
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.Ratings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ReceptId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Predobar doner.",
                            InsertTime = new DateTime(2020, 8, 10, 22, 12, 58, 204, DateTimeKind.Local).AddTicks(6530),
                            KorisnikId = 1,
                            Mark = 4,
                            ReceptId = 2
                        });
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.ReceptKoraci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Deskripcija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.Property<int>("RedniBrojKoraka")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceptId");

                    b.ToTable("ReceptKoraci");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deskripcija = "Priprema sosa za prekrivanje mesa.",
                            ReceptId = 2,
                            RedniBrojKoraka = 1
                        },
                        new
                        {
                            Id = 2,
                            Deskripcija = "Przenje mesa.",
                            ReceptId = 2,
                            RedniBrojKoraka = 2
                        },
                        new
                        {
                            Id = 3,
                            Deskripcija = "Jedenje.",
                            ReceptId = 2,
                            RedniBrojKoraka = 3
                        },
                        new
                        {
                            Id = 4,
                            Deskripcija = "Ubrati grah.",
                            ReceptId = 1,
                            RedniBrojKoraka = 1
                        },
                        new
                        {
                            Id = 5,
                            Deskripcija = "Skuhati.",
                            ReceptId = 1,
                            RedniBrojKoraka = 2
                        },
                        new
                        {
                            Id = 6,
                            Deskripcija = "Dodati suhog mesa.",
                            ReceptId = 1,
                            RedniBrojKoraka = 3
                        });
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.ReceptSastojci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kolicina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceptId");

                    b.ToTable("ReceptSastojci");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kolicina = "1 kilgoram",
                            Naziv = "Telece meso.",
                            ReceptId = 2
                        },
                        new
                        {
                            Id = 2,
                            Kolicina = "1 kilgoram",
                            Naziv = "Telece meso.",
                            ReceptId = 2
                        },
                        new
                        {
                            Id = 3,
                            Kolicina = "1 kilgoram",
                            Naziv = "Telece meso.",
                            ReceptId = 2
                        });
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.Recepti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BrojPregleda")
                        .HasColumnType("bigint");

                    b.Property<int>("DuzinaPripreme")
                        .HasColumnType("int");

                    b.Property<int?>("GlavnaSlikaId")
                        .HasColumnType("int");

                    b.Property<int>("KategorijeId")
                        .HasColumnType("int");

                    b.Property<int>("KnjigaRecepataId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GlavnaSlikaId");

                    b.HasIndex("KategorijeId");

                    b.HasIndex("KnjigaRecepataId");

                    b.ToTable("Recepti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojPregleda = 0L,
                            DuzinaPripreme = 30,
                            KategorijeId = 7,
                            KnjigaRecepataId = 1,
                            Naziv = "Domaci Nanin Grah",
                            Public = true
                        },
                        new
                        {
                            Id = 2,
                            BrojPregleda = 0L,
                            DuzinaPripreme = 30,
                            KategorijeId = 4,
                            KnjigaRecepataId = 1,
                            Naziv = "Doner Kebab iz srca Turske",
                            Public = true
                        });
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.Uloge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Uloge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "User"
                        });
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.KnjigeRecepata", b =>
                {
                    b.HasOne("recipe_guru.WebAPI.Database.Korisnici", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.Korisnici", b =>
                {
                    b.HasOne("recipe_guru.WebAPI.Database.Uloge", "Uloge")
                        .WithMany()
                        .HasForeignKey("UlogeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.Ratings", b =>
                {
                    b.HasOne("recipe_guru.WebAPI.Database.Korisnici", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recipe_guru.WebAPI.Database.Recepti", "Recept")
                        .WithMany("Ratings")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.ReceptKoraci", b =>
                {
                    b.HasOne("recipe_guru.WebAPI.Database.Recepti", "Recept")
                        .WithMany("ReceptKoraci")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.ReceptSastojci", b =>
                {
                    b.HasOne("recipe_guru.WebAPI.Database.Recepti", "Recept")
                        .WithMany("ReceptSastojci")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("recipe_guru.WebAPI.Database.Recepti", b =>
                {
                    b.HasOne("recipe_guru.WebAPI.Database.ImageResources", "GlavnaSlika")
                        .WithMany()
                        .HasForeignKey("GlavnaSlikaId");

                    b.HasOne("recipe_guru.WebAPI.Database.Kategorije", "Kategorije")
                        .WithMany()
                        .HasForeignKey("KategorijeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recipe_guru.WebAPI.Database.KnjigeRecepata", "KnjigaRecepata")
                        .WithMany("Recepti")
                        .HasForeignKey("KnjigaRecepataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
